apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: post-tap-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting app"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting app"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install
      ref: origin/main
      subPath: post-packaging
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt: {}

  deploy:
  - kapp: {}