apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton-pipelines
  namespace: tap-install
spec:
  packageRef:
    refName: tekton.tanzu.vmware.com
    versionSelection:
      constraints: 0.33.5
  serviceAccountName: tap-install-sa