apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/change-group: "rbac"
  name: tap-install-gitops-sa
  namespace: tap-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kapp.k14s.io/change-group: "rbac"
  name: tap-install-gitops-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kapp.k14s.io/change-group: "rbac"
  name: tap-install-gitops-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-install-gitops-cluster-role
subjects:
- kind: ServiceAccount
  name: tap-install-gitops-sa
  namespace: tap-install