apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-gui-cert
  namespace: tap-gui
spec:
  commonName: tap-gui.postcvs.tapsme.org
  dnsNames:
  - tap-gui.postcvs.tapsme.org
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: tap-gui-cert-secret