apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-gui-ssl-delegation
  namespace: tap-gui
spec:
  delegations:
    - secretName: tap-gui-cert-secret
      targetNamespaces:
      - "*"