apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-gui-cert
  namespace: tap-gui
spec:
  commonName: server.tap-gui.svc
  dnsNames:
  - server.tap-gui.svc
  - server.tap-gui.svc.cluster.local
  - appliveview.cvsdr.tapsme.org
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: tap-gui-cert-secret