apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-pkg"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-pkg"
  name: tap-gui-vanity
  namespace: tap-gui
spec:
  routes:
  - services:
    - name: server
      port: 7000
  virtualhost:
    fqdn: vanity.cvs.tapsme.org