#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespaces
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - inline:
      pathsFrom:
      - secretRef:
          name: app-onboarding-files
  template:
  - ytt:
      ignoreUnknownComments: true
      valuesFrom:
      - secretRef:
          name: namespace-names
  deploy:
  - kapp: 
      rawOptions: 
      - --diff-changes=true
---
apiVersion: v1
kind: Secret
metadata:
  name: namespace-names
stringData:
  values.yaml: #@ yaml.encode({ "namespaces": data.values.namespaces })
---
apiVersion: v1
kind: Secret
metadata:
  name: app-onboarding-files
stringData:
  additional-users.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@ load("@ytt:base64", "base64")
    #@ load("@ytt:json", "json")
    #@ load("@ytt:yaml", "yaml")

    #@ for ns in data.values.namespaces:
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: #@ ns
    #@ end
