#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespaces
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - inline:
      pathsFrom:
      - secretRef:
          name: app-onboarding-files
  template:
  - ytt:
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            namespaces:
            - caleb
            - jeff
            - jeremy
            - robert
  deploy:
  - kapp: 
      rawOptions: 
      - --diff-changes=true
---
apiVersion: v1
kind: Secret
metadata:
  name: app-onboarding-files
stringData:
  additional-users.yaml: |
    #@ load("@ytt:data", "data")
    #@ for ns in data.values.namespaces:
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: #@ ns
    #@ end
