#@ load("@ytt:data", "data")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespaces
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - inline:
      paths:
        additional-users.yaml: |
          #@ load("@ytt:data", "data")
          #@ for ns in data.values.namespaces:
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: #@ ns
          #@ end
  template:
  - ytt:
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            namespaces:
            - justin
            - mae
            - aiden
            - travis
  deploy:
  - kapp: 
      rawOptions: 
      - --diff-changes=true