apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tbs-full-deps-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: index.docker.io/tapsme/tbs-full-deps:1.6.0
      secretRef: 
        name: tap-registry
        namespace: tap-install