#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-source-pipelinerun
spec:
  outputs:
    url: spec.params[?(@.name=="source-url")].value
    revision: spec.params[?(@.name=="source-revision")].value

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      workspaces:
        - name: maven-settings
          subPath: maven-repo-cache
          persistentVolumeClaim:
            claimName: supplychain-pvc
        - name: supplychain-workspace
          persistentVolumeClaim:
            claimName: supplychain-pvc
      pipelineRef:
        name: $(selected.metadata.name)$
      params:
      - name: source-url
        value: $(runnable.spec.inputs.source-url)$
      - name: source-revision
        value: $(runnable.spec.inputs.source-revision)$
