apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rehan-addons
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-tenant-onboarding
      ref: origin/custom
      subPath: tenants/rehan
      secretRef: 
        name: tap-install-gitops-ssh
  template:
    - ytt:
        inline:
          paths:
            overlay.yaml: |
              #@ load("@ytt:overlay", "overlay")
              #@overlay/match by=overlay.all, expects="1+"
              ---
              metadata:
                #@overlay/match missing_ok=True
                namespace: rehan
  deploy:
  - kapp:
      rawOptions:
      - --diff-changes=true