apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-install-gitops
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting rbac"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting rbac"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install
      ref: origin/main
      subPath: packaging
      secretRef: 
        name: tap-install-gitops-ssh
  template:
  - ytt: {}

  deploy:
  - kapp:
      rawOptions:
      - --wait-resource-timeout=5m
      - --diff-changes=true