apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: secret-to-be-created
    creationPolicy: Owner

  data:

  - secretKey: example-externalsecret-key
    remoteRef:
      key: example-externalsecret-key
