apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: tap-values-external-secret
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: |
          profile: run
          ceip_policy_disclosed: true

          shared:
            ingress_domain: run.postcvs.tapsme.org

          supply_chain: basic

          contour:
            envoy:
              service:
                type: LoadBalancer

          appliveview_connector:
            backend:
              ingressEnabled: true
              host: appliveview.postcvs.tapsme.org
              port: "443"
              sslDisabled: false
              caCertData: | 
              {{ .alvconnectorcacert | b64dec }}

          appsso:
            domain_name: "run.postcvs.tapsme.org"
            
  data:
  - secretKey: alvconnectorcacert
    remoteRef:
      key: alvconnectorcacert