apiVersion: v1
data:
  tap-values.yml: cHJvZmlsZTogcnVuCmNlaXBfcG9saWN5X2Rpc2Nsb3NlZDogdHJ1ZQoKc2hhcmVkOgogIGluZ3Jlc3NfZG9tYWluOiBydW4ucG9zdGN2cy50YXBzbWUub3JnCgpzdXBwbHlfY2hhaW46IGJhc2ljCgpjb250b3VyOgogIGVudm95OgogICAgc2VydmljZToKICAgICAgdHlwZTogTG9hZEJhbGFuY2VyCgphcHBsaXZldmlld19jb25uZWN0b3I6CiAgYmFja2VuZDoKICAgIGhvc3Q6IGFwcGxpdmV2aWV3LnBvc3RjdnMudGFwc21lLm9yZwogICAgcG9ydDogIjQ0MyIKICAgIHNzbERpc2FibGVkOiAiZmFsc2UiCiAgICBpbmdyZXNzRW5hYmxlZDogInRydWUi
kind: Secret
metadata:
  creationTimestamp: null
  name: tap-tap-install-values
  namespace: tap-install