apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: tap-values-external-secret
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: |
          profile: run
          ceip_policy_disclosed: true

          shared:
            ingress_domain: run.postcvs.tapsme.org
            ca_cert_data: |
              -----BEGIN CERTIFICATE-----
              MIIDPjCCAiagAwIBAgIRAPmsOFGD09V2lx/pfzAZSBkwDQYJKoZIhvcNAQELBQAw
              KDEPMA0GA1UEChMGdm13YXJlMRUwEwYDVQQLEwx2bXdhcmUgbWFtYmcwHhcNMjIx
              MDE5MTkzNTM4WhcNMjMwMTE3MTkzNTM4WjAoMQ8wDQYDVQQKEwZ2bXdhcmUxFTAT
              BgNVBAsTDHZtd2FyZSBtYW1iZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
              ggEBAL7eDv84bhqUlFau9EmmqVsdYglZ+yLigtiDyk0xTpA5GfTdbWVusElYGQdz
              +mkSUfkl9cVkA1syGVEszH/pqmkhCda0FoViK9W+d/zl0Rj5/5pNCvrUt3TATuLr
              RL116hvQF4cE7Js7rJOQ4ZJFfgPMQ+kHf1WfNn/QuZuBumtmLeDMgrA7+bH4z1/7
              DamrPeyYaYg/6R1C+3T9xZaQmopJAXKpSZmHghSJGDdmyppzeAas+ip+75ygHr0F
              zgYfU2dFtiM70mTzUZtWsVKcnU7iAB6ZHpDI4SooEHfZfGwdXj7IAoduCqgrv3tr
              eMah4K3Dg0WY2qyVDhInEfxYNTkCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8G
              A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPtYcSihKVCdoaiqWVomo2n+hoAWMB8G
              A1UdEQQYMBaCFCoucG9zdGN2cy50YXBzbWUub3JnMA0GCSqGSIb3DQEBCwUAA4IB
              AQBO//myBfiTWTGJrwKqEyb9+bb08SyZRtYNTK1rHeF4JyS3R7Zz4BDvbBZJGARg
              qiDOgTl34ATvSVPRx54dcD/s/dBVcKxfG0cXIj0UydtZMrGHat6SO1EBVqfmf/CB
              XTq9rKVaQvzJKRL9rSCscFfXRmK+zhq/H9ElkfCGwKxGkA7aEwQ3ou6ryhbnnp1p
              nYrFQUOw5Kcck3zmQrLA8q2FFd8+yNqlSbHTr+LyIpZakZqSRu2jv5d28opm2Qtz
              YY/Thqj1tDkFHrNkUKlihU5PgSbYTjdrM+gIjE592szYwUQXZiodu73+9sjmMphK
              j5CMlPEOc1BHYfr8lyjPytvr
              -----END CERTIFICATE-----

          contour:
            envoy:
              service:
                type: LoadBalancer

          appliveview_connector:
            backend:
              ingressEnabled: true
              host: appliveview.postcvs.tapsme.org
              port: "443"
              sslDisabled: false
              caCertData: | 
                -----BEGIN CERTIFICATE-----
                MIIDPjCCAiagAwIBAgIRAPmsOFGD09V2lx/pfzAZSBkwDQYJKoZIhvcNAQELBQAw
                KDEPMA0GA1UEChMGdm13YXJlMRUwEwYDVQQLEwx2bXdhcmUgbWFtYmcwHhcNMjIx
                MDE5MTkzNTM4WhcNMjMwMTE3MTkzNTM4WjAoMQ8wDQYDVQQKEwZ2bXdhcmUxFTAT
                BgNVBAsTDHZtd2FyZSBtYW1iZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
                ggEBAL7eDv84bhqUlFau9EmmqVsdYglZ+yLigtiDyk0xTpA5GfTdbWVusElYGQdz
                +mkSUfkl9cVkA1syGVEszH/pqmkhCda0FoViK9W+d/zl0Rj5/5pNCvrUt3TATuLr
                RL116hvQF4cE7Js7rJOQ4ZJFfgPMQ+kHf1WfNn/QuZuBumtmLeDMgrA7+bH4z1/7
                DamrPeyYaYg/6R1C+3T9xZaQmopJAXKpSZmHghSJGDdmyppzeAas+ip+75ygHr0F
                zgYfU2dFtiM70mTzUZtWsVKcnU7iAB6ZHpDI4SooEHfZfGwdXj7IAoduCqgrv3tr
                eMah4K3Dg0WY2qyVDhInEfxYNTkCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8G
                A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPtYcSihKVCdoaiqWVomo2n+hoAWMB8G
                A1UdEQQYMBaCFCoucG9zdGN2cy50YXBzbWUub3JnMA0GCSqGSIb3DQEBCwUAA4IB
                AQBO//myBfiTWTGJrwKqEyb9+bb08SyZRtYNTK1rHeF4JyS3R7Zz4BDvbBZJGARg
                qiDOgTl34ATvSVPRx54dcD/s/dBVcKxfG0cXIj0UydtZMrGHat6SO1EBVqfmf/CB
                XTq9rKVaQvzJKRL9rSCscFfXRmK+zhq/H9ElkfCGwKxGkA7aEwQ3ou6ryhbnnp1p
                nYrFQUOw5Kcck3zmQrLA8q2FFd8+yNqlSbHTr+LyIpZakZqSRu2jv5d28opm2Qtz
                YY/Thqj1tDkFHrNkUKlihU5PgSbYTjdrM+gIjE592szYwUQXZiodu73+9sjmMphK
                j5CMlPEOc1BHYfr8lyjPytvr
                -----END CERTIFICATE-----

          appsso:
            domain_name: "run.postcvs.tapsme.org"

          api_auto_registration:
            logging_profile: development
            tap_gui_url: "https://tap-gui.postcvs.tapsme.org"
            ca_cert_data: |
              -----BEGIN CERTIFICATE-----
              MIIDPjCCAiagAwIBAgIRAPmsOFGD09V2lx/pfzAZSBkwDQYJKoZIhvcNAQELBQAw
              KDEPMA0GA1UEChMGdm13YXJlMRUwEwYDVQQLEwx2bXdhcmUgbWFtYmcwHhcNMjIx
              MDE5MTkzNTM4WhcNMjMwMTE3MTkzNTM4WjAoMQ8wDQYDVQQKEwZ2bXdhcmUxFTAT
              BgNVBAsTDHZtd2FyZSBtYW1iZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
              ggEBAL7eDv84bhqUlFau9EmmqVsdYglZ+yLigtiDyk0xTpA5GfTdbWVusElYGQdz
              +mkSUfkl9cVkA1syGVEszH/pqmkhCda0FoViK9W+d/zl0Rj5/5pNCvrUt3TATuLr
              RL116hvQF4cE7Js7rJOQ4ZJFfgPMQ+kHf1WfNn/QuZuBumtmLeDMgrA7+bH4z1/7
              DamrPeyYaYg/6R1C+3T9xZaQmopJAXKpSZmHghSJGDdmyppzeAas+ip+75ygHr0F
              zgYfU2dFtiM70mTzUZtWsVKcnU7iAB6ZHpDI4SooEHfZfGwdXj7IAoduCqgrv3tr
              eMah4K3Dg0WY2qyVDhInEfxYNTkCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8G
              A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPtYcSihKVCdoaiqWVomo2n+hoAWMB8G
              A1UdEQQYMBaCFCoucG9zdGN2cy50YXBzbWUub3JnMA0GCSqGSIb3DQEBCwUAA4IB
              AQBO//myBfiTWTGJrwKqEyb9+bb08SyZRtYNTK1rHeF4JyS3R7Zz4BDvbBZJGARg
              qiDOgTl34ATvSVPRx54dcD/s/dBVcKxfG0cXIj0UydtZMrGHat6SO1EBVqfmf/CB
              XTq9rKVaQvzJKRL9rSCscFfXRmK+zhq/H9ElkfCGwKxGkA7aEwQ3ou6ryhbnnp1p
              nYrFQUOw5Kcck3zmQrLA8q2FFd8+yNqlSbHTr+LyIpZakZqSRu2jv5d28opm2Qtz
              YY/Thqj1tDkFHrNkUKlihU5PgSbYTjdrM+gIjE592szYwUQXZiodu73+9sjmMphK
              j5CMlPEOc1BHYfr8lyjPytvr
              -----END CERTIFICATE-----

          cnrs:
            default_tls_secret: "tap-install/workload-cert"
            ca_cert_data: |
              -----BEGIN CERTIFICATE-----
              MIIDPjCCAiagAwIBAgIRAPmsOFGD09V2lx/pfzAZSBkwDQYJKoZIhvcNAQELBQAw
              KDEPMA0GA1UEChMGdm13YXJlMRUwEwYDVQQLEwx2bXdhcmUgbWFtYmcwHhcNMjIx
              MDE5MTkzNTM4WhcNMjMwMTE3MTkzNTM4WjAoMQ8wDQYDVQQKEwZ2bXdhcmUxFTAT
              BgNVBAsTDHZtd2FyZSBtYW1iZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
              ggEBAL7eDv84bhqUlFau9EmmqVsdYglZ+yLigtiDyk0xTpA5GfTdbWVusElYGQdz
              +mkSUfkl9cVkA1syGVEszH/pqmkhCda0FoViK9W+d/zl0Rj5/5pNCvrUt3TATuLr
              RL116hvQF4cE7Js7rJOQ4ZJFfgPMQ+kHf1WfNn/QuZuBumtmLeDMgrA7+bH4z1/7
              DamrPeyYaYg/6R1C+3T9xZaQmopJAXKpSZmHghSJGDdmyppzeAas+ip+75ygHr0F
              zgYfU2dFtiM70mTzUZtWsVKcnU7iAB6ZHpDI4SooEHfZfGwdXj7IAoduCqgrv3tr
              eMah4K3Dg0WY2qyVDhInEfxYNTkCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgKkMA8G
              A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFPtYcSihKVCdoaiqWVomo2n+hoAWMB8G
              A1UdEQQYMBaCFCoucG9zdGN2cy50YXBzbWUub3JnMA0GCSqGSIb3DQEBCwUAA4IB
              AQBO//myBfiTWTGJrwKqEyb9+bb08SyZRtYNTK1rHeF4JyS3R7Zz4BDvbBZJGARg
              qiDOgTl34ATvSVPRx54dcD/s/dBVcKxfG0cXIj0UydtZMrGHat6SO1EBVqfmf/CB
              XTq9rKVaQvzJKRL9rSCscFfXRmK+zhq/H9ElkfCGwKxGkA7aEwQ3ou6ryhbnnp1p
              nYrFQUOw5Kcck3zmQrLA8q2FFd8+yNqlSbHTr+LyIpZakZqSRu2jv5d28opm2Qtz
              YY/Thqj1tDkFHrNkUKlihU5PgSbYTjdrM+gIjE592szYwUQXZiodu73+9sjmMphK
              j5CMlPEOc1BHYfr8lyjPytvr
              -----END CERTIFICATE-----
  data:
  - secretKey: alvconnectorcacert
    remoteRef:
      key: alvconnectorcacert
  - secretKey: tapguitlscacert
    remoteRef:
      key: tapguitlscacert
      