apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-registry-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: tap-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .tapregistry | toString }}"

  data:
  - secretKey: tapregistry
    remoteRef:
      key: tapregistry
