apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: tap-values-external-secret
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: |
          profile: run
          ceip_policy_disclosed: true

          shared:
            ingress_domain: run.postcvs.tapsme.org

          supply_chain: basic

          contour:
            envoy:
              service:
                type: LoadBalancer

          appliveview_connector:
            backend:
              ingressEnabled: true
              host: appliveview.postcvs.tapsme.org
              port: "443"
              sslDisabled: false
              caCertData: | 
          {{ .alvconnectorcacert | b64dec }}

          appsso:
            domain_name: "run.postcvs.tapsme.org"

          api_auto_registration:
            logging_profile: development
            tap_gui_url: "https://tap-gui.postcvs.tapsme.org"
            ca_cert_data: |
              -----BEGIN CERTIFICATE-----
              MIIDGzCCAgOgAwIBAgIQaGCcRYJeualoAwhH61BxjDANBgkqhkiG9w0BAQsFADAl
              MSMwIQYDVQQDExp0YXAtZ3VpLnBvc3RjdnMudGFwc21lLm9yZzAeFw0yMjEwMTgx
              NjAxMjlaFw0yMzAxMTYxNjAxMjlaMCUxIzAhBgNVBAMTGnRhcC1ndWkucG9zdGN2
              cy50YXBzbWUub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2v2q
              mr5u6hM5qZJTyzsWap679YI965hULUGYLFFioH9+BaNgXXkwSzDtO1l5L+07kEye
              MvFFnE4+GeLMJCIBnmHT+X7PjWtoz71nl8HXHI/vJVc7ECL/RHVKZtUdqcJqKmsT
              NsJQbA83NtH+1gOUzfA8zIutiKf002OdViBoQ8j6hDeUMS9NO5ZI2LdjHCHqOBGH
              SrblNHR2ECCRG4F+SGJV7BTIHJ7pQnKHZ0UN+xlxVelHeBATWqP5TTFdh2s9SsPj
              7UXgcxXjPO5Nl1e6Wlb+0BHfScBu/uCCk+KEuS06O+D8UCm+k0MePPK3+/t7/9Qe
              Wp0hTpdGBroW8ebrVwIDAQABo0cwRTAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/
              BAIwADAlBgNVHREEHjAcghp0YXAtZ3VpLnBvc3RjdnMudGFwc21lLm9yZzANBgkq
              hkiG9w0BAQsFAAOCAQEADEfQg5yOwzKf3YQCTY3cglZ+3ZqqXoqAkCvigQKGVelt
              zaHRVp0HBDkjQzHuXNqSqkmtIEj94oK40BE4Y1nquwqxW+JA9JnQCL+vw7Q2Vyul
              8BI/yz+O6ES2tBhjdedsn2iSqtr00FFftEmNX4DJoVKwBZ/IXCBwLOkiwEcMKRFn
              Vxx3cKlBX0zcEtVQQhROT2H3mI1i99HqPa1jLAY2fX7/s5gW51pq5NCoDb+RdFYw
              hLFHoBkavE8XNUvgwvei9nIqK3DikeCSDpKSFK29+JHgnl4x6T5rgHMHsxNdyEb9
              9iHXayP11IkAjdtorkebQ5QebIW8tqUdBZTWVuHbfQ==
              -----END CERTIFICATE-----
          
          cnrs:
            domain_name: run.postcvs.tapsme.org
            default_tls_secret: "tap-install/workload-cert-secret"
            ca_cert_data: |
              -----BEGIN CERTIFICATE-----
              MIIDQzCCAiugAwIBAgIRAKeQo7YK15krb0AG90/KoeowDQYJKoZIhvcNAQELBQAw
              IzEhMB8GA1UEAwwYKi5ydW4ucG9zdGN2cy50YXBzbWUub3JnMB4XDTIyMTAxODE5
              NTMxMVoXDTIzMDExNjE5NTMxMVowIzEhMB8GA1UEAwwYKi5ydW4ucG9zdGN2cy50
              YXBzbWUub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1UAZFp+8
              +7/z6AjWurnYQeIroe18ScC1iEwP+kBvwjLSusEX4T1IYFTPBxzwmPOyoQrNHei7
              mCBFH+OF30vnIK57l4c394WVtM3KQ4gH8W/dn3XDkNsSBtazigY6A8Sct4Nia+0x
              rhVIqfjbapopnhm2K2/rOX5FTgcMqtS0svo5ea1gL1g0OQXQ0lvCmd4QCPwBV5ro
              57LfnagXY3E0Q20smfRVQVss1RxwB+RzEyP9zyzbNpPGUM4fi/3sFNaHw/rKSV94
              PJAyF69WdoRyW79BOOT/bjv8h6LNUHkWv1YbgjiC1J1B1L+Kzi+mRd1oJuTDjM3w
              BhzLRRbuwYk4TQIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIw
              ADBQBgNVHREESTBHgitjdXN0b21lci1wcm9maWxlLm1hZS5ydW4ucG9zdGN2cy50
              YXBzbWUub3JnghgqLnJ1bi5wb3N0Y3ZzLnRhcHNtZS5vcmcwDQYJKoZIhvcNAQEL
              BQADggEBABny2ol6CFyiJzouuTeyKJEc2XPYK6540dHO7ibEaasnDsb0af/6dFcH
              HgcgmtePIMVOil6lKqKt0idV62ylKr3tR0TUzjg8DSAW8mP1/m5Z/fgetBrYkC5W
              2UOHMnY7HlvP4xrSmV9PDzCBHEn5vyyPUni6IL/QijOSzTuPv39//tUxjrSSI759
              W+UQyeeepQxR7/SgmB7XMQuyWtISADPCihA4kI7ZUGkbHU2t7JJRHIK6ZYUmMuSF
              J7S+QEAt1zDAhLcPo3r5iyiHLJ6obZk05LOCW7v+7xaf3Q9culTq4zNWFLUEfAvE
              dC2AvpSFTaN9E0PDWFUxngj+fEct80k=
              -----END CERTIFICATE-----
  data:
  - secretKey: alvconnectorcacert
    remoteRef:
      key: alvconnectorcacert
  - secretKey: tapguitlscacert
    remoteRef:
      key: tapguitlscacert
  - secretKey: cnrscacert
    remoteRef:
      key: cnrscacert
      