apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: accelerator-cert
  namespace: tap-install
spec:
  secretName: accelerator-cert
  isCA: false
  dnsNames:
  - accelerator.postcvs.tapsme.org
  issuerRef:
    name: post-cvs-full-ca-issuer