apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-live-view-cert
  namespace: tap-install
spec:
  secretName: app-live-view-cert
  isCA: false
  dnsNames:
  - appliveview.postcvs.tapsme.org
  issuerRef:
    name: post-cvs-full-ca-issuer
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: appliveview-cert-delegation
  namespace: tap-install
spec:
  delegations:
    - secretName: app-live-view-cert
      targetNamespaces:
      - app-live-view 