apiVersion: v1
kind: Secret
metadata:
  name: grype-offline
  namespace: tap-install
type: Opaque
stringData:
        grype-overlay.yaml: |
            #@ load("@ytt:overlay", "overlay")

            apiVersion: v1
            kind: Secret
            metadata:
              name: patch-grype
              namespace: tap-install
            stringData:
              patch-grype.yaml: |
                      #@ load("@ytt:overlay", "overlay")

                      apiVersion: v1
                      kind: ConfigMap
                      metadata:
                        name: ca-cert
                        namespace: default 
                      data:
                        custom-ca.crt: |
                                -----BEGIN CERTIFICATE-----
                                MIIFXzCCA0egAwIBAgIJAJYm37SFocjlMA0GCSqGSIb3DQEB
                                7NyEv1C1YdQCJV9NkiAV5aIRlImnrKVowhaTXoK33X+YkR0=
                                -----END CERTIFICATE-----

                      #@overlay/match by=overlay.subset({"kind": "ScanTemplate"}), expects="1+"
                      ---
                      spec:
                        template:
                          initContainers:
                            #@overlay/match by=overlay.subset({"name": "scan-plugin"})
                             - name: scan-plugin
                               #@overlay/match missing_ok=True
                               env:
                               #@overlay/append
                                - name: GRYPE_CHECK_FOR_APP_UPDATE
                                  value: "false"
                                - name: GRYPE_DB_AUTO_UPDATE
                                  value: "true"
                                - name: GRYPE_DB_UPDATE_URL
                                  value: http://10.0.107.44/listing.json
                                - name: GRYPE_DB_CA_CERT
                                  value: "/etc/ssl/certs/custom-ca.crt"
                               volumeMounts:
                                  #@overlay/append
                                  - name: ca-cert
                                    mountPath: /etc/ssl/certs/custom-ca.crt
                                    subPath: custom-ca.crt
                          volumes:
                          #@overlay/append
                          - name: ca-cert
                            configMap:
                              name: ca-cert
            #@overlay/match by=overlay.subset({"kind":"PackageInstall","metadata":{"name":"grype"}})
            ---
            metadata:
              #@overlay/match missing_ok=True
              annotations:
                #@overlay/match missing_ok=True
                ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: patch-grype