#@ load("@ytt:data", "data")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespaces
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - inline:
      paths:
        config.yaml: |
          #@ load("@ytt:data", "data")
          #@ for ns in data.values.namespaces:
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: #@ ns.name
            labels:
              apps.tanzu.vmware.com/tap-ns: ""
          #@ end
  template:
  - ytt:
      ignoreUnknownComments: true
      valuesFrom:
      - secretRef:
          name: namespace-names
  deploy:
  - kapp: 
      rawOptions: 
      - --diff-changes=true
---
apiVersion: v1
kind: Secret
metadata:
  name: namespace-names
stringData:
  values.yaml: #@ yaml.encode({ "namespaces": data.values.namespaces })