#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespaces
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: ssh://git@github.com/Mpluya/tap-install
      ref: origin/1.4
      secretRef: 
        name: tap-install-gitops-ssh-external-secret
  template:
  - ytt:
      paths:
      - namespace-provisioner
      valuesFrom:
      - secretRef:
          name: tap-values-external-secret
  deploy:
  - kapp: 
      rawOptions: ["--dangerous-override-ownership-of-existing-resources=true"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! This annotation tells the provisioner app to not override this configMap as this is your desired state.
data:
  namespaces.yaml: #@ yaml.encode({"namespaces": data.values.namespaces })