#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: namespaces
  namespace: tap-install
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - inline:
      paths:
        config.yaml: |
          #@ load("@ytt:data", "data")
          #@ for ns in namespaces():
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: #@ ns.name
          labels:
            apps.tanzu.vmware.com/tap-ns: ""
          #@ end
  template:
  - ytt:
      paths:
      - namespace-provisioner
  deploy:
  - kapp:
      rawOptions:
      - --dangerous-override-ownership-of-existing-resources=true
      - --diff-changes=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! This annotation tells the provisioner app to not override this configMap as this is your desired state.
data:
  namespaces.yaml: #@ '#@data/values' + "\n---\n" + yaml.encode(config())