apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-pkg"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-pkg"
  name: snyk
  namespace: tap-install
spec:
  packageRef:
    refName: snyk.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: "1.0.0-beta.3"
      prereleases: {}
  serviceAccountName: tap-tap-install-sa
  values:
  - secretRef:
      name: snyk-install-values
