apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: tap-values-external-secret
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: full
          ceip_policy_disclosed: true

          shared:
            ingress_domain: postcvs.tapsme.org

          buildservice:
            kp_default_repository: "tapsme/tbs"
            kp_default_repository_username: "tapsme"
            kp_default_repository_password: "{{ .kpdefaultrepositorypassword  }}"
            tanzunet_username: "mlarge@vmware.com"
            tanzunet_password:  "{{ .tanzunetpassword  }}" 

          supply_chain: testing_scanning

          metadata_store:
            app_service_type: ClusterIP #! (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
            ns_for_export_app_cert: "*"

            db_name: metadata_store
            db_host: msdocs-postgresql-server-417762730.postgres.database.azure.com
            db_user: "azureuser@msdocs-postgresql-server-417762730"
            db_password: "{{ .metadatastoredbpassword  }}"
            deploy_internal_db: "false"
            db_ca_certificate: {{ .metadatastoredbcacert }}

          ootb_supply_chain_basic:
            registry:
              server: index.docker.io
              repository: tapsme
            gitops:
              ssh_secret: "gitops-ssh"
              branch: main
              pull_request:
                server_kind: github
                commit_branch: ""
                pull_request_title: ready for review
                pull_request_body: generated by supply chain

          ootb_supply_chain_testing_scanning:
            registry:
              server: index.docker.io
              repository: tapsme
            gitops:
              ssh_secret: "gitops-ssh"
              server_address: "ssh://git@github.com"
              repository_owner: "Mpluya"
              repository_name: "config-polaris-demo"
              branch: main
                
          learningcenter:
            ingressClass: contour

          contour:
            envoy:
              service:
                type: LoadBalancer

          tap_gui:
            tls:
              namespace: tap-gui
              secretName: tap-gui-cert-secret
            service_type: ClusterIP
            ingressEnabled: "true"
            app_config:
              auth:
                environment: development
                providers:
                  github:
                    development:
                      clientId: 54fdbb4861dcfc46b9aa
                      clientSecret: "{{ .githubauthclientsecret  }}"
              kubernetes:
                serviceLocatorMethod:
                  type: 'multiTenant'
                clusterLocatorMethods:
                  - type: 'config'
                    clusters:
                      - url: https://post-cvs-r-cvsresourcegroup-489753-c2d834c4.hcp.eastus.azmk8s.io:443
                        name: post-cvs-run
                        authProvider: serviceAccount
                        serviceAccountToken: "{{ .postcvsrunserviceaccounttoken  }}"
                        skipTLSVerify: false
                        caData: {{ .postcvsruncadata }}
                      - url: https://post-cvs-cvsresourcegroup-489753-e27cb78d.hcp.eastus.azmk8s.io:443
                        name: post-cvs
                        authProvider: serviceAccount
                        serviceAccountToken: "{{ .postcvsserviceaccounttoken  }}"
                        skipTLSVerify: false
                        caData: {{ .postcvscadata }}

              proxy:
                /metadata-store:
                  target: https://metadata-store-app.metadata-store:8443/api/v1
                  changeOrigin: true
                  secure: false
                  headers:
                    Authorization: "{{ .metadatastoreauthheader  }}"
                    X-Custom-Source: project-star
              app:
                baseUrl: https://tap-gui.postcvs.tapsme.org
              integrations:
                github:
                - host: github.com
                  token: {{ .githubintegrationtoken }}
              catalog:
                locations:
                - type: url
                  target: https://github.com/Mpluya/tap-gui-catalog/blob/main/catalog-info.yaml
              backend:
                baseUrl: https://tap-gui.postcvs.tapsme.org
                cors:
                  origin: https://tap-gui.postcvs.tapsme.org
                reading:
                  allow:
                  - host: "*.postcvs.tapsme.org"
                database:
                  client: pg
                  connection:
                    host: msdocs-postgresql-server-417762730.postgres.database.azure.com
                    port: 5432
                    user: "azureuser@msdocs-postgresql-server-417762730"
                    password: "{{ .tapguipostgresspassword  }}"
                  prefix: 'post_cvs_'

          excluded_packages:
            - image-policy-webhook.signing.apps.tanzu.vmware.com
            - ootb-delivery-basic.tanzu.vmware.com
            - policy.apps.tanzu.vmware.com
            - service-bindings.labs.vmware.com
            - services-toolkit.tanzu.vmware.com
            - cnrs.tanzu.vmware.com
            - sso.apps.tanzu.vmware.com
            - connector.appliveview.tanzu.vmware.com
            - grype.scanning.apps.tanzu.vmware.com
            
          ootb_templates:
            excluded_templates:
              - 'tekton-source-pipelinerun'
              - 'testing-pipeline'

          accelerator:
            ingress:
              include: true
              enable_tls: true
            tls:
              secret_name: tap-gui-cert-secret
              namespace: tap-gui

          appliveview:
            ingressEnabled: true
            tls:
              secretName: app-live-view-cert-secret
              namespace: app-live-view         
            
  data:
  - secretKey: metadatastoredbpassword
    remoteRef:
      key: metadatastoredbpassword
  - secretKey: metadatastoredbcacert
    remoteRef:
      key: metadatastoredbcacert
  - secretKey: kpdefaultrepositorypassword
    remoteRef:
      key: kpdefaultrepositorypassword
  - secretKey: tanzunetpassword
    remoteRef:
      key: tanzunetpassword
  - secretKey: postcvsrunserviceaccounttoken
    remoteRef:
      key: postcvsrunserviceaccounttoken
  - secretKey: postcvsruncadata
    remoteRef:
      key: postcvsruncadata
  - secretKey: postcvsserviceaccounttoken
    remoteRef:
      key: postcvsserviceaccounttoken
  - secretKey: postcvscadata
    remoteRef:
      key: postcvscadata
  - secretKey: metadatastoreauthheader
    remoteRef:
      key: metadatastoreauthheader
  - secretKey: githubintegrationtoken
    remoteRef:
      key: githubintegrationtoken
  - secretKey: tapguipostgresspassword
    remoteRef:
      key: tapguipostgresspassword
  - secretKey: githubauthclientsecret
    remoteRef:
      key: githubauthclientsecret