apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: "tap-pkg"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-packageinstall-setup"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-packageinstall-setup"
    packaging.carvel.dev/downgradable: ""
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: "grype-offline"
  name: tap
  namespace: tap-install
spec:
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: ">1.0.0"
      prereleases: {}
  serviceAccountName: tap-tap-install-sa
  values:
  - secretRef:
      name: tap-tap-install-values
