apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-gui-cert
  namespace: tap-install
spec:
  secretName: tap-gui-cert
  isCA: false
  dnsNames:
  - server.tap-gui.svc
  - server.tap-gui.svc.cluster.local
  - tap-gui.postcvs.tapsme.org
  issuerRef:
    name: post-cvs-full-ca-issuer
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tap-gui-cert-delegation
  namespace: tap-install
spec:
  delegations:
    - secretName: tap-gui-cert
      targetNamespaces:
      - tap-gui