apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tap-eso-vault

  target:
    name: tap-values-external-secret
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: full
          ceip_policy_disclosed: true

          shared:
            ingress_domain: learn.tapsme.org

          buildservice:
            kp_default_repository: "tapsme/tbs"
            kp_default_repository_username: "tapsme"
            kp_default_repository_password: "{{ .kpdefaultrepositorypassword  }}"
            tanzunet_username: "mlarge@vmware.com"
            tanzunet_password:  "{{ .tanzunetpassword  }}" 

          supply_chain: ""

          metadata_store:
            app_service_type: ClusterIP #! (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
            ns_for_export_app_cert: "*"

            db_name: metadata_store
            db_host: msdocs-postgresql-server-417762730.postgres.database.azure.com
            db_user: "azureuser@msdocs-postgresql-server-417762730"
            db_password: "{{ .metadatastoredbpassword  }}"
            deploy_internal_db: "false"
            db_ca_certificate: |
              -----BEGIN CERTIFICATE-----
              MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ
              RTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD
              VQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX
              DTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y
              ZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVy
              VHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKr
              mD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjr
              IZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeK
              mpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSu
              XmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZy
              dc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM71oGDHweI12v/ye
              jl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1
              BE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3
              DQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT92
              9hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3Wgx
              jkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0
              Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhz
              ksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRCwBXbsdtTLS
              R9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp
              -----END CERTIFICATE-----
              -----BEGIN CERTIFICATE-----
              MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh
              MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
              d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
              MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT
              MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
              b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG
              9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI
              2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx
              1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ
              q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz
              tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ
              vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP
              BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV
              5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY
              1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4
              NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG
              Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91
              8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe
              pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl
              MrY=
              -----END CERTIFICATE-----

          ootb_supply_chain_basic:
            registry:
              server: index.docker.io
              repository: tapsme
            gitops:
              ssh_secret: "gitops-ssh"
              branch: main
              pull_request:
                server_kind: github
                commit_branch: ""
                pull_request_title: ready for review
                pull_request_body: generated by supply chain

          ootb_supply_chain_testing_scanning:
            registry:
              server: index.docker.io
              repository: tapsme
            gitops:
              ssh_secret: "gitops-ssh"
              server_address: "ssh://git@github.com"
              repository_owner: "Mpluya"
              repository_name: "config-polaris-demo"
              branch: main
            scanning:
              image:
                template: prisma-private-image-scan-template
                policy: scan-policy
              source:
                template: prisma-blob-source-scan-template
                policy: scan-policy

          learningcenter:
            ingressClass: contour

          contour:
            envoy:
              service:
                type: LoadBalancer

          tap_gui:
            tls:
              namespace: tap-install
              secretName: tap-gui-cert
            service_type: ClusterIP
            ingressEnabled: "true"
            app_config:
              auth:
                environment: development
                providers:
                  github:
                    development:
                      clientId: 54fdbb4861dcfc46b9aa
                      clientSecret: "{{ .githubauthclientsecret  }}"

              proxy:
                /metadata-store:
                  target: https://metadata-store-app.metadata-store:8443/api/v1
                  changeOrigin: true
                  secure: false
                  headers:
                    Authorization: "{{ .metadatastoreauthheader  }}"
                    X-Custom-Source: project-star
              app:
                baseUrl: https://tap-gui.learn.tapsme.org
              integrations:
                github:
                - host: github.com
                  token: {{ .githubintegrationtoken }}
              catalog:
                locations:
                - type: url
                  target: https://github.com/Mpluya/tap-gui-catalog/blob/main/catalog-info.yaml
              backend:
                baseUrl: https://tap-gui.learn.tapsme.org
                cors:
                  origin: https://tap-gui.learn.tapsme.org
                reading:
                  allow:
                  - host: "*.learn.tapsme.org"
                database:
                  client: pg
                  connection:
                    host: msdocs-postgresql-server-417762730.postgres.database.azure.com
                    port: 5432
                    user: "azureuser@msdocs-postgresql-server-417762730"
                    password: "{{ .tapguipostgresspassword  }}"
                  prefix: 'post_cvs_'

          excluded_packages:
            - image-policy-webhook.signing.apps.tanzu.vmware.com
            - ootb-delivery-basic.tanzu.vmware.com
            - policy.apps.tanzu.vmware.com
            - service-bindings.labs.vmware.com
            - services-toolkit.tanzu.vmware.com
            - cnrs.tanzu.vmware.com
            - sso.apps.tanzu.vmware.com
            - connector.appliveview.tanzu.vmware.com
            - grype.scanning.apps.tanzu.vmware.com
            - ootb-supply-chain-basic.tanzu.vmware.com
            - ootb-supply-chain-testing.tanzu.vmware.com
            - ootb-supply-chain-testing-scanning.tanzu.vmware.com
            
          accelerator:
            ingress:
              include: true
              enable_tls: true
            tls:
              secret_name: accelerator-cert
              namespace: tap-install
          appliveview:
            ingressEnabled: true
            tls:
              secretName: app-live-view-cert
              namespace: tap-install        
            
  data:
  - secretKey: metadatastoredbpassword
    remoteRef:
      key: metadatastoredbpassword
  - secretKey: kpdefaultrepositorypassword
    remoteRef:
      key: kpdefaultrepositorypassword
  - secretKey: tanzunetpassword
    remoteRef:
      key: tanzunetpassword
  - secretKey: metadatastoreauthheader
    remoteRef:
      key: metadatastoreauthheader
  - secretKey: githubintegrationtoken
    remoteRef:
      key: githubintegrationtoken
  - secretKey: tapguipostgresspassword
    remoteRef:
      key: tapguipostgresspassword
  - secretKey: githubauthclientsecret
    remoteRef:
      key: githubauthclientsecret