#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-tap-install-values
  namespace: tap-install
type: Opaque
stringData:
  tap-values.yaml: #@ yaml.encode(data.values.tap)

