apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-packageinstall-setup"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-packageinstall-setup"
    packaging.carvel.dev/downgradable: ""
  name: full-tbs-deps
  namespace: tap-install
spec:
  packageRef:
    refName: full-tbs-deps.tanzu.vmware.com
    versionSelection:
      constraints: "1.6.0"
      prereleases: {}
  serviceAccountName: tap-tap-install-sa
